const ACTIONS = {
    MAKE_REQUEST: 'MAKE_REQUEST',
    GET_ALL_VEHICLES: 'GET_ALL_VEHICLES',
    FILTER_VEHICLES: 'FILTER_VEHICLES',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SHOW_ERROR: 'SHOW_ERROR'
}

export default ACTIONS;